sudo: required
dist: trusty
group: deprecated-2017Q3

language: python

env:
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=pycodestyle
    - TEST_SUITE=pydocstyle
    - TEST_SUITE=unit-tests
    - TEST_SUITE=tests
    - TEST_SUITE=mypy

python:
  - "3.6"

# commands to install dependencies
before_install:
  - sudo apt-get install libtcmalloc-minimal4
  - export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
  - easy_install distribute
  - pip install -r requirements.txt
  - if [ -f tests/$TEST_SUITE""_requirements.txt ]; then pip install -r tests/$TEST_SUITE""_requirements.txt; fi
  - if [ -f tests/$TEST_SUITE""_install.sh ]; then tests/$TEST_SUITE""_install.sh; fi

# command to run tests
script: tests/$TEST_SUITE""_run.sh
